language: java
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk6

before_install:
    - chmod +x gradlew

script:
    - TERM=dumb ./gradlew clean build dist

after_success:
    - TERM=dumb ./gradlew jacocoTestReport coveralls

sudo: false

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

notifications:
    email:
        - skylot@gmail.com
